### ISSUE TITLE
Ruby SDK is not working.

### ISSUE THREAD

**Issue by alexizmailov** [messagemedia/messages-ruby-sdk#4]
Ruby example with my credentials and my phone number (+61 and so on):
```
root@ext-somehost-01:~  #./sms.rb
 INFO  MessageMediaMessages::MessagesController : Instantiated controller class.
 INFO  MessageMediaMessages::DeliveryReportsController : Instantiated controller class.
 INFO  MessageMediaMessages::RepliesController : Instantiated controller class.
 INFO  MessageMediaMessages::MessagesController : create_send_messages called.
 INFO  MessageMediaMessages::MessagesController : Preparing query URL for create_send_messages.
 INFO  MessageMediaMessages::MessagesController : Preparing headers for create_send_messages.
 INFO  MessageMediaMessages::MessagesController : Preparing and executing HttpRequest for create_send_messages.
 INFO  MessageMediaMessages::MessagesController : Merging global headers with endpoint headers for create_send_messages.
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/faraday-0.10.1/lib/faraday/request/retry.rb:30: warning: constant ::Fixnum is deprecated
 INFO  MessageMediaMessages::MessagesController : Wrapping request and response in a context object for create_send_messages.
 INFO  MessageMediaMessages::MessagesController : Validating response for create_send_messages.
ERROR  MessageMediaMessages::MessagesController : <MessageMediaMessages::APIException> HTTP Response Not OK
	/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/messagemedia_messages_sdk-1.0.0/lib/message_media_messages/controllers/base_controller.rb:53:in `validate_response'
	/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/messagemedia_messages_sdk-1.0.0/lib/message_media_messages/controllers/messages_controller.rb:323:in `create_send_messages'
	sms.rb:25:in `<main>'
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/messagemedia_messages_sdk-1.0.0/lib/message_media_messages/controllers/base_controller.rb:53:in `validate_response': HTTP Response Not OK (MessageMediaMessages::APIException)
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/messagemedia_messages_sdk-1.0.0/lib/message_media_messages/controllers/messages_controller.rb:323:in `create_send_messages'
	from sms.rb:25:in `<main>'
```

**Comment by JamesDale** [comment]
Thinking this may also be something to do with authentication. If you would like to send your code to james.dale@messagemedia.com.au I'll take a look into it. Thanks :)

**Comment by alexizmailov** [comment]
Closed, my fault - credentials from SOAP don't work with REST.
